site_name: BWS SDK Documentation
site_description: Pure Python implementation of the BW Secrets API
site_author: rippleFCL
site_url: https://overengineers-anonymous.github.io/bws-sdk/

repo_name: Overengineers-Anonymous/bws-sdk
repo_url: https://github.com/Overengineers-Anonymous/bws-sdk

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: true
            show_submodules: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - Client: api/client.md
    - Types: api/types.md
    - Crypto: api/crypto.md
    - Token: api/token.md
    - Errors: api/errors.md
  - Examples: examples.md
  - Changelog: changelog.md

docs_dir: docs
site_dir: site

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Overengineers-Anonymous/bws-sdk
