[build]
  publish = "site"
  command = "pip install poetry && poetry install && poetry run mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.13"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[context.production]
  command = "pip install poetry && poetry install && poetry run mkdocs build"

[context.deploy-preview]
  command = "pip install poetry && poetry install && poetry run mkdocs build"

[context.branch-deploy]
  command = "pip install poetry && poetry install && poetry run mkdocs build"
